---
title: "HW2 PSTAT 131"
output: html_document
date: "2022-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(tidyverse)
library(moments)
library(labelled)
 
```

```{r}
aba <-read.csv("abalone.csv", header=TRUE)
View(aba)


```

##1

```{r}
#adds the age column to the dataset (rigs column +1.5)
aba$age <- (aba$rings+1.5)

#Barplot of counts of ages of abalone 
Age_barplot <- ggplot(aba, aes(x=age)) + geom_histogram()

#mean age is 11.43 years
mean(aba$age)

#variance is 10.40 years
var(aba$age)

#barplot of counts of abalone age, data is positively skewed
Age_barplot

```

##2 
```{r}
#sets seed
set.seed(66668888)
#splits the data with 80% used for training and 20% for testing
aba_split <- initial_split(aba, prop = 0.80,
                                strata = age)
aba_train <- training(aba_split)
aba_test <- testing(aba_split)



```

##3

```{r}
# cant use rings to predict age as age is just rings with 1.5 added to it


#creates our recipe for model
aba_recipe_basic <- recipe(age ~ type + longest_shell + diameter + height+whole_weight + shucked_weight+ viscera_weight + shell_weight,  data= aba_train) %>%
 step_dummy_multi_choice(all_nominal_predictors()) 

aba_recipe <- aba_recipe_basic %>% step_interact(terms = ~ starts_with("type"):shucked_weight)%>%

step_interact(terms = ~ longest_shell:diameter) %>% step_interact(terms=  ~ shucked_weight:shell_weight) %>%
step_zv(all_numeric_predictors()) %>%
step_normalize(all_numeric_predictors()) %>%
prep()
      

```

##4
```{r}
#creates our linear regression model
lm_model <- linear_reg() %>% set_engine("lm")

```

##5
```{r}
#creates workflow for our linear regression model 
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(aba_recipe)

```

##6
``` {r }
#female abalone that we wnat to predict age of
abaF <-data.frame(longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1, type="F")

#fits our training data to our workflow
aba_fit <- fit(lm_wflow,aba_train)
abaF$age <- predict(aba_fit,abaF, type = "numeric")

#predicts the the abalone is 22.14 years old
View(abaF)
```
##7 Create a metric set with R^2, RMSE, MAE. Will create a predicted models from testing data and compare to actual observed ages

``` {r}

aba_metrics <- metric_set(rsq,rmse,mae)

#predicts age from test data
aba_test_pred_age <- predict(aba_fit,aba_test, type = "numeric")


#predicts age from training data
aba_train_pred_age <- predict(aba_fit,aba_train, type = "numeric")

aba_test_final <-bind_cols(aba_test,aba_test_pred_age, id = NULL)

aba_train_final <-bind_cols(aba_train,aba_train_pred_age, id = NULL)

names(aba_train_final)[names(aba_train_final) == '.pred'] <- 'predicted_age'

names(aba_test_final)[names(aba_test_final) == '.pred'] <- 'predicted_age'

#produces metrics on our test data
aba_metrics(aba_test_final,truth= age, estimate = predicted_age)

#produces metrics on our training data
aba_metrics(aba_train_final,truth= age, estimate = predicted_age)
```
on our testing data: R^2 value is .512, rmse is 2.174, mae is 1.542. This means that 51.2% of variance our data can be explained by our model.
 
on our training data: R^2 value is .563, rmse is 2.149, mae is 1.544. This means that 56.3% of variance our data can be explained by our model.

